name: xiaoheifs-postgres

services:
  xiaoheifs:
    build:
      context: ../..
      dockerfile: docker/build/Dockerfile
    image: xiaoheifs-backend:latest
    # Alpine variant:
    # image: xiaoheifs-backend:alpine
    container_name: xiaoheifs
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      APP_ADDR: ":8080"
      APP_API_BASE_URL: "http://localhost:8080"
      APP_JWT_SECRET: ""
      APP_PLUGIN_MASTER_KEY: ""
      APP_PLUGINS_DIR: "./backend/plugins"
      APP_DB_TYPE: postgres
      APP_DB_PATH: ""
      APP_DB_HOST: "postgres"
      APP_DB_PORT: "5432"
      APP_DB_NAME: "xiaoheifs"
      APP_DB_USER: "xiaoheifs"
      APP_DB_PASSWORD: "XiaoheiFS123$%^"
      APP_DB_OPTIONS: "sslmode=disable TimeZone=Asia/Shanghai"
    volumes:
      - xiaoheifs_data:/app/data
      - xiaoheifs_uploads:/app/uploads
    depends_on:
      - postgres
    networks:
      - xiaoheifs

  postgres:
    image: postgres:17
    container_name: xiaoheifs-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: xiaoheifs
      POSTGRES_USER: xiaoheifs
      POSTGRES_PASSWORD: 'XiaoheiFS123$%^'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - xiaoheifs

volumes:
  xiaoheifs_data:
  xiaoheifs_uploads:
  postgres_data:

networks:
  xiaoheifs:
    name: xiaoheifs
